#!/usr/bin/env python3
"""Build styles.css, the stylesheet Obsidian loads with the plugin.

  build_styles.py [--check]

styles.css = src/plugin.css (the banner, lights and settings page) followed by the
four theme files in theme/ (lcars-core, lcars-motion, lcars-nn-rows,
lcars-folder-focus), in that order. Installing the plugin therefore installs the
theme. Style Manager reads the @settings block that lives in lcars-core from this
stylesheet.

Edit src/plugin.css and theme/*.css, then run this. styles.css is generated: do not
edit it by hand. With --check it changes nothing and exits 1 if styles.css is stale.
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = ["src/plugin.css", "theme/lcars-core.css", "theme/lcars-motion.css",
         "theme/lcars-nn-rows.css", "theme/lcars-folder-focus.css"]
BANNER = ("/* ============================================================\n"
          "   styles.css is GENERATED by tools/build_styles.py. Edit src/plugin.css and\n"
          "   theme/*.css instead, then run the script.\n"
          "   ============================================================ */\n")

def build():
    out = [BANNER]
    for p in PARTS:
        text = open(os.path.join(ROOT, p), encoding="utf-8").read().rstrip("\n")
        out.append("\n/* ######## %s ######## */\n%s\n" % (p, text))
    return "".join(out)

if __name__ == "__main__":
    new = build()
    path = os.path.join(ROOT, "styles.css")
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
    if "--check" in sys.argv:
        print("styles.css is up to date" if old == new else "styles.css is STALE: run tools/build_styles.py")
        sys.exit(0 if old == new else 1)
    open(path, "w", encoding="utf-8").write(new)
    print("wrote styles.css: %d bytes from %d parts" % (len(new.encode()), len(PARTS)))
