#!/usr/bin/env python3
"""Generate the MOTION-OFF block for a CSS file.

For every rule that declares an animation, and for every rule inside an
@media (prefers-reduced-motion: reduce) block, emit the same rule gated on a
body class, so one switch turns motion off. Coverage is by construction: add an
animation, run this again, and it is covered.

  gen_motion_off.py FILE --gate ".lcars-motion-off" [--before MARKER] [--extra FILE] [--write]

Without --write it prints what it would do. The block sits between
MOTION-OFF begin/end markers and is replaced on every run.
"""
import re, sys, argparse

BEGIN = "/* MOTION-OFF begin (generated by tools/gen_motion_off.py; edit the generator or the rules above, not this block) */"
END = "/* MOTION-OFF end */"

def blank_comments(s):
    return re.sub(r'/\*.*?\*/', lambda m: re.sub(r'[^\n]', ' ', m.group(0)), s, flags=re.S)

def parse(s, media=""):
    """Yield (selector, body, media) for every style rule, recursing into media/supports."""
    i, n, out = 0, len(s), []
    start = 0
    while i < n:
        c = s[i]
        if c in "\"'":
            q = c; i += 1
            while i < n and s[i] != q:
                i += 2 if s[i] == "\\" else 1
            i += 1; continue
        if c == ";":
            start = i + 1; i += 1; continue
        if c == "}":
            start = i + 1; i += 1; continue
        if c == "{":
            prelude = s[start:i].strip()
            d, j = 1, i + 1
            while j < n and d:
                if s[j] in "\"'":
                    q = s[j]; j += 1
                    while j < n and s[j] != q: j += 2 if s[j] == "\\" else 1
                elif s[j] == "{": d += 1
                elif s[j] == "}": d -= 1
                j += 1
            body = s[i + 1:j - 1]
            if prelude.startswith("@"):
                name = re.match(r"@([\w-]+)", prelude).group(1).lower()
                if name in ("media", "supports", "layer", "container"):
                    out += parse(body, (media + " " + prelude).strip())
            elif prelude:
                out.append((prelude, body, media))
            start = i = j; continue
        i += 1
    return out

def split_top(sel):
    parts, d, cur = [], 0, ""
    for ch in sel:
        if ch in "([": d += 1
        elif ch in ")]": d -= 1
        if ch == "," and d == 0: parts.append(cur.strip()); cur = ""
        else: cur += ch
    if cur.strip(): parts.append(cur.strip())
    return parts

BODY = re.compile(r'(^|[\s>+~(,])body(?![\w-])')
def gate(sel, g):
    if BODY.search(sel):
        return BODY.sub(lambda m: m.group(1) + "body" + g, sel, count=1)
    m = re.match(r'^(html[^\s>+~]*|:root[^\s>+~]*)(\s+|\s*[>+~]\s*)?(.*)$', sel)
    if m and m.group(3):
        return m.group(1) + " body" + g + " " + m.group(3)
    return "body" + g + " " + sel

ANIM = re.compile(r'(^|[;{\s])animation(-name)?\s*:\s*(?!none\b)')
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("file"); ap.add_argument("--gate", required=True)
    ap.add_argument("--before"); ap.add_argument("--extra"); ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    src = open(a.file).read()
    # drop any previous block
    if BEGIN in src:
        i = src.index(BEGIN); j = src.index(END, i) + len(END)
        src = src[:i].rstrip("\n") + "\n" + src[j:].lstrip("\n")
    rules = parse(blank_comments(src))
    g = a.gate if a.gate.startswith(":is(") else a.gate
    anim, mirror = [], []
    for sel, body, media in rules:
        reduced = "prefers-reduced-motion" in media
        if reduced:
            for s1 in split_top(sel):
                mirror.append((gate(s1, g), re.sub(r"\s+", " ", body).strip()))
        elif ANIM.search(body):
            anim += [gate(s1, g) for s1 in split_top(sel)]
    seen, anim_u = set(), []
    for s1 in anim:
        if s1 not in seen: seen.add(s1); anim_u.append(s1)
    lines = [BEGIN]
    if a.extra: lines.append(open(a.extra).read().rstrip("\n"))
    if anim_u:
        lines.append(",\n".join(anim_u) + " {\n  animation: none !important;\n}")
    for sel, body in mirror:
        lines.append(sel + " { " + body + " }")
    lines.append(END)
    block = "\n".join(lines) + "\n"
    if a.write:
        if a.before:
            k = src.index(a.before)
            k = src.rfind("\n", 0, k) + 1
            # step back to the start of the comment banner that holds the marker
            c = src.rfind("/*", 0, k + len(a.before))
            k = src.rfind("\n", 0, c) + 1 if c >= 0 else k
            new = src[:k] + block + "\n" + src[k:]
        else:
            new = src.rstrip("\n") + "\n\n" + block
        open(a.file, "w").write(new)
    print(f"{a.file}: {len(rules)} rules parsed, {len(anim_u)} animated selectors, {len(mirror)} mirrored reduced-motion rules, block {len(block)} bytes" + (" (written)" if a.write else " (dry run)"))
    return block

if __name__ == "__main__":
    b = main()
    if "--show" in sys.argv: print(b)
